### ISSUE TITLE
Merging the Github Login branch with the develop main branch

### ISSUE THREAD

**Issue by JulianStaab** [rwth-acis/VIAProMa#197] opened 2021-03-31 09:06 UTC
Since the [learninglayers_login](https://github.com/rwth-acis/VIAProMa/tree/learninglayers_login) branch is now fully functional, even though no features like creating or editing issue are implemented on it, the login features should be added to the develop branch as part of the idea of making merge-request smaller to prevent too many collisions.

**Comment by EmilieHK** [comment] 2021-04-12 06:13
Since the extending branch "reqbazandgithublogin_ui" contains all features from this branch and has been merged into the develop branch, there is not further need to merge this branch into the develop branch. The issue is closed.

**Closed by EmilieHK** 2021-04-12 06:13 UTC
Labels: enhancement
