### ISSUE TITLE
Server access problem while building backend

### ISSUE THREAD

**Issue by EmilieHK** [rwth-acis/VIAProMa#57] opened 2020-05-15 10:59 UTC
### How to recreate
When running the `ant get_deps` command in the backend folder of the project, the building of the backend fails as the ivy server can only be accessed with the https protocol. However, the xml-file only uses http.

### Help for fixing the bug
Replacing http with https in the xml-file should solve this problem.

**Comment by JulianStaab** [comment] 2020-05-15 11:00
The problem is now fixed and tested in the connectionlines_WindowAdjust branch.

**Closed by JulianStaab** 2020-05-15 11:00 UTC
Labels: bug
